services:
  frontend:
    platform: linux/amd64
    image: aidenregistry.azurecr.io/frontend
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
  backend:
    platform: linux/amd64
    image: aidenregistry.azurecr.io/backend
    build: ./backend
