services:
  - type: web
    name: frontend
    runtime: docker
    buildCommand: docker build -t frontend ./frontend
    envVars:
      - key: PORT
        value: 3000
  - type: web
    name: backend
    runtime: docker
    buildCommand: docker build -t backend ./backend
    envVars:
      - key: PORT
        value: 8000